# Generated by Django 5.1.5 on 2025-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Опубликовать продукт?"),
        ),
    ]
